### ISSUE TITLE
Add the solar exoatmospheric spectral irradiances

### ISSUE THREAD

**Issue by m-mohr** [stac-extensions/view#3]
Ported from stac-spec. @fabricerito wrote in https://github.com/radiantearth/stac-spec/issues/852:

> Hello,
> 
> The View Geometry Extension provides the **view:sun_azimuth** and **view:sun_elevation**. (https://github.com/radiantearth/stac-spec/tree/master/extensions/view)
> 
> If we add a **view:eai** for the exoatmospheric spectral irradiances (a.k.a. ESUN in several radiance to reflectance formulas) we would have all the information to do the optical calibration reading all the info from the STAC item:
> 
> * sun azimuth
> * sun elevation
> * solar exoatmospheric spectral irradiance (band-dependent)
> 
> While Landsat-8 doesn't need this info, Landsat 1-7, Kompsat-2/3/3a, SPOT-6/7, CBERS-4, Gaofen-1 (just to name a few) would certainly benefit from this.
> 
> See section "Solar exoatmospheric spectral irradiances (ESUN) for the Landsat 1-7 data" of https://www.usgs.gov/land-resources/nli/landsat/using-usgs-landsat-level-1-data-product

See https://github.com/radiantearth/stac-spec/issues/852 for more comments from @cholmes and @matthewhanson.

**Comment by emmanuelmathot** [comment]
I proposed the value in a PR for `eo` as the value is per band and related to electro-optical data: https://github.com/stac-extensions/eo/pull/4

**Comment by m-mohr** [comment]
Moved to eo
