### ISSUE TITLE
OpenAPI spec needs to provide for when fields are only on Assets and not in Properties

### ISSUE THREAD

**Issue by philvarner** [stac-extensions/view#4]
Currently, the spec only allows these attributes to be in Item Properties. However, there may be some utility is allowing them in Assets also. The current sentinel2 stactools package puts the per-asset `view:azimuth` and `view:incidence_angle` in the Asset. 

Should these attributes also be allowed in Assets by the spec?

**Comment by matthewhanson** [comment]
These can be added to assets as well. Any property defined in an extension can be used at the Item of Asset level as per https://github.com/radiantearth/stac-spec/blob/master/item-spec/item-spec.md#additional-fields-for-assets

**Comment by philvarner** [comment]
Ah, so knowing that, I think we need to add a section like in EO https://github.com/stac-extensions/eo/blob/b4f74a350c6ced21d63217d2adb45eeb5096089e/json-schema/schema.json#L32 to does a conditional check if the attributes are defined in assets. 

I should have led this question with the problem I'm actually seeing - validation via the json schema fails if the Item *only* has the view attributes defined in the assets, and not also in Properties.

**Comment by m-mohr** [comment]
The JSON Schema allows and validates them in assets (https://github.com/stac-extensions/view/blob/main/json-schema/schema.json#L40), but the README was not overly clear on this. I've updated the section to correctly reflect for which scopes the fields are allowed.
